services:
  api:
    image: ghcr.io/${OWNER:-cpe-4irc-eyjafjallajokull}/app-qg-api:${IMAGE_TAG:-latest}
    container_name: app-qg-api
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]
    environment:
      - APP_NAME=${APP_NAME:-app-qg-api}
      - APP_ENVIRONMENT=${APP_ENVIRONMENT:-production}
      - APP_DEBUG=${APP_DEBUG:-false}
      - APP_LOG_LEVEL=${APP_LOG_LEVEL:-INFO}
      - APP_POSTGRES_DSN=${APP_POSTGRES_DSN}
      - APP_RABBITMQ_DSN=${APP_RABBITMQ_DSN}
      - APP_EVENTS_PING_INTERVAL_SECONDS=${APP_EVENTS_PING_INTERVAL_SECONDS:-30}
    restart: unless-stopped
    networks:
      - proxy
      - databases
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-qg-api.rule=Host(`${API_HOST:-api.sdmis.mathislambert.fr}`)"
      - "traefik.http.routers.app-qg-api.entrypoints=websecure"
      - "traefik.http.routers.app-qg-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.app-qg-api.loadbalancer.server.port=8000"

networks:
  proxy:
    external: true
  databases:
    external: true
