services:
  api:
    image: ghcr.io/${OWNER:-cpe-4irc-eyjafjallajokull}/app-qg-api:${IMAGE_TAG:-latest}
    container_name: app-qg-api
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "4"]
    environment:
      - APP_VERSION=${APP_VERSION:-latest}
      - APP_NAME=${APP_NAME:-app-qg-api}
      - APP_ENVIRONMENT=${APP_ENVIRONMENT:-production}
      - APP_DEBUG=${APP_DEBUG:-false}
      - APP_CORS_ORIGINS=${APP_CORS_ORIGINS:-*}
      - APP_LOG_LEVEL=${APP_LOG_LEVEL:-INFO}
      - APP_EVENTS_PING_INTERVAL_SECONDS=${APP_EVENTS_PING_INTERVAL_SECONDS:-25}
      - POSTGRES_DSN=${POSTGRES_DSN}
      - RABBITMQ_DSN=${RABBITMQ_DSN}
      - AUTH_DISABLED=${AUTH_DISABLED:-false}
      - KEYCLOAK_SERVER_URL=${KEYCLOAK_SERVER_URL:-http://localhost:8080}
      - KEYCLOAK_REALM=${KEYCLOAK_REALM:-master}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID:-app-qg-api}
      - KEYCLOAK_AUDIENCE=${KEYCLOAK_AUDIENCE:-app-qg-api}
      - KEYCLOAK_CACHE_TTL_SECONDS=${KEYCLOAK_CACHE_TTL_SECONDS:-300}
      - KEYCLOAK_TIMEOUT_SECONDS=${KEYCLOAK_TIMEOUT_SECONDS:-3.0}
    restart: unless-stopped
    networks:
      - proxy
      - databases
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-qg-api.rule=Host(`${API_HOST:-api.sdmis.mathislambert.fr}`)"
      - "traefik.http.routers.app-qg-api.entrypoints=websecure"
      - "traefik.http.routers.app-qg-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.app-qg-api.loadbalancer.server.port=8000"

networks:
  proxy:
    external: true
  databases:
    external: true
